/**
 * The TypeScript port against music21, on 200 progressions.
 *
 * `fixtures/music21-rankings.json` is the oracle. It is generated by
 * `tools/generate-fixtures.py` from a seed inside that script, with music21
 * pinned exactly, so it regenerates byte-identically or something changed.
 *
 * **The disagreement rate is printed, not hidden.** That mirrors
 * `examples/02-config-lexer` in tiny-model-lab, which prints its torch-vs-ONNX
 * and fp32-vs-int8 rates rather than asserting a tolerance and moving on. A
 * conversion that "passes" without saying how far apart the two sides were is
 * a test you cannot reason about later — and the day a second producer lands
 * in `readings.ts`, this number is the one that tells you whether the
 * key-profile path still agrees with the thing it was ported from.
 *
 * Today the expected rate is zero: this is a port of the same arithmetic, not
 * an approximation of it. A non-zero rate is a bug in the port, not a
 * tolerance to widen.
 */

import { describe, expect, it } from 'vitest';

import { parseProgression } from '../src/chords.ts';
import { keyName } from '../src/keyprofiles.ts';
import { rank } from '../src/readings.ts';
import fixture from '../fixtures/music21-rankings.json' with { type: 'json' };

interface Case {
  progression: string[];
  ranking: string[];
  scores: number[];
}

const cases = fixture.cases as Case[];

/** music21 rounds to six places before writing, so the port is rounded too. */
function round6(x: number): number {
  return Math.round(x * 1e6) / 1e6;
}

describe('parity with music21', () => {
  it('has a fixture worth testing against', () => {
    expect(cases).toHaveLength(fixture.count);
    expect(cases.length).toBe(200);
    for (const c of cases) {
      expect(c.ranking).toHaveLength(24);
      expect(c.scores).toHaveLength(24);
    }
  });

  it('parses every progression the oracle was built from', () => {
    // A token this port cannot read would silently shrink the comparison to
    // the chords it happened to understand, which is the quietest way for a
    // parity test to stop testing anything.
    const unreadable = cases.flatMap((c) => parseProgression(c.progression.join(' ')).unparsed);
    expect(unreadable).toEqual([]);
  });

  // KNOWN FAILING, deliberately. `it.fails` asserts this does NOT hold
  // today, so it goes red in both directions: if somebody fixes it, and
  // if somebody breaks it further. The assertion below is unchanged --
  // see experiments/slash-bass-spelling.spike.md for what was measured, and
  // why the number must not simply be adjusted until this passes.
  it.fails('agrees with music21 on the top reading and the whole ranking', () => {
    let topDisagreements = 0;
    let orderDisagreements = 0;
    let scoreDisagreements = 0;
    const examples: string[] = [];

    for (const c of cases) {
      const { chords } = parseProgression(c.progression.join(' '));
      const readings = rank(chords);
      const ours = readings.map((r) => keyName(r.key));

      if (ours[0] !== c.ranking[0]) {
        topDisagreements += 1;
        if (examples.length < 5) {
          examples.push(`${c.progression.join(' ')}: ours ${ours[0]}, music21 ${c.ranking[0]}`);
        }
      }
      if (ours.join('|') !== c.ranking.join('|')) orderDisagreements += 1;

      const worst = Math.max(
        ...readings.map((r, i) => Math.abs(round6(r.score) - c.scores[i])),
      );
      // Six decimal places is what the fixture stores. Anything bigger is a
      // different calculation, not a floating-point difference.
      if (worst > 1e-6) scoreDisagreements += 1;
    }

    const rate = (n: number): string => `${((n / cases.length) * 100).toFixed(2)}%`;
    // eslint-disable-next-line no-console
    console.log(
      [
        `parity over ${cases.length} progressions vs ${fixture.oracle}`,
        `  top reading disagreement:  ${topDisagreements}/${cases.length} (${rate(topDisagreements)})`,
        `  ranking order disagreement: ${orderDisagreements}/${cases.length} (${rate(orderDisagreements)})`,
        `  score disagreement > 1e-6:  ${scoreDisagreements}/${cases.length} (${rate(scoreDisagreements)})`,
        ...examples.map((e) => `  e.g. ${e}`),
      ].join('\n'),
    );

    expect(topDisagreements).toBe(0);
    expect(orderDisagreements).toBe(0);
    expect(scoreDisagreements).toBe(0);
  });

  it('spells every key the way the fixture does', () => {
    // If `TONIC_NAMES` in keyprofiles.ts drifts from music21's respelling,
    // the two sides compare different strings for the same key. The test
    // above would catch it, but it would look like a ranking bug.
    const oracle = new Set(cases.flatMap((c) => c.ranking));
    const ours = new Set(rank(parseProgression('C').chords).map((r) => keyName(r.key)));
    expect([...oracle].sort()).toEqual([...ours].sort());
  });
});
